type: workflow
name: subdomain_recon
alias: subrec
description: Subdomain discovery
tags: [recon, dns, takeovers]
input_types:
  - host
tasks:
  subfinder:
    description: List subdomains (passive)
  # dnsxbrute:
  #   description: Bruteforce subdomain (active)
  #   targets_:
  #     - type: target
  #       field: 'FUZZ.{name}'
  # TODO: add subdomain bruteforcers
  # gobuster:
  #   input: vhost
  #   domain_:
  #     - target.name
  #   wordlist: /usr/share/seclists/Discovery/DNS/combined_subdomains.txt
  # gobuster:
  #   input: dns
  #   domain_:
  #     - target.name
  #   wordlist: /usr/share/seclists/Discovery/DNS/combined_subdomains.txt
  _group:
    nuclei:
      description: Check for subdomain takeovers
      targets_:
      - target.name
      - subdomain.host
      tags: [takeover, dns]
    httpx:
      description: Run HTTP probes on subdomains
      targets_:
      - target.name
      - subdomain.host
    dnsx:
      description: Get DNS records for subdomains
      targets_:
      - target.name
      - subdomain.host